# Generated by Django 2.0.6 on 2018-10-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
