# Generated by Django 2.0.6 on 2018-12-02 23:26

from django.db import migrations, models
import partners.validators


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20181022_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermeeting',
            name='num_coffee',
            field=models.SmallIntegerField(default=0, validators=[partners.validators.meeting_coffee_validator], verbose_name='커모 횟수'),
        ),
        migrations.AlterField(
            model_name='partnermeeting',
            name='num_eat',
            field=models.SmallIntegerField(default=0, validators=[partners.validators.meeting_eat_validator], verbose_name='밥모 횟수'),
        ),
    ]
