# Generated by Django 2.0.6 on 2018-06-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationscheme',
            options={'verbose_name': '운영 정보', 'verbose_name_plural': '운영 정보'},
        ),
    ]
