# Generated by Django 2.0.6 on 2018-07-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedphotos',
            options={'verbose_name': '사진', 'verbose_name_plural': '사진'},
        ),
    ]
