# Generated by Django 2.0.6 on 2018-10-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagram',
            options={'verbose_name': '인스타그램', 'verbose_name_plural': '인스타그램'},
        ),
    ]
