# Generated by Django 2.0.6 on 2018-07-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180630_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationscheme',
            name='coffee_point',
            field=models.FloatField(default=2.0, help_text='실수형 점수입니다. 예: 2.0', verbose_name='커모 1회당 점수'),
        ),
        migrations.AddField(
            model_name='operationscheme',
            name='eat_point',
            field=models.FloatField(default=1.0, help_text='실수형 점수입니다. 예: 2.0', verbose_name='밥모 1회당 점수'),
        ),
        migrations.AlterField(
            model_name='operationscheme',
            name='semester_end',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='학기 종료일'),
        ),
    ]
