# Generated by Django 2.0.6 on 2018-07-04 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180701_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationscheme',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.ActiveUser'),
        ),
        migrations.AlterField(
            model_name='operationscheme',
            name='semester_start',
            field=models.DateField(help_text='1학기는 3월 2일, 2학기는 9월 1일', verbose_name='학기 시작일'),
        ),
    ]
