# Generated by Django 2.0.6 on 2018-10-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181009_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationscheme',
            name='extra_2_point',
            field=models.FloatField(default=1.0, help_text='윗짝지 1명, 아래짝지 1명인 모임에서, 2명이 모두 모였을 때 추가로 부여하는 점수입니다.\n아래짝지 1명 모이면 커모점수 + 추가점수', verbose_name='2인 추가점수'),
        ),
        migrations.AddField(
            model_name='operationscheme',
            name='extra_3_point',
            field=models.FloatField(default=0.5, help_text='윗짝지 1명, 아래짝지 2명인 모임에서, 3명이 모두 모였을 때 추가로 부여하는 점수입니다.\n아래짝지 1명 모이면 커모점수. 2명 모이면 커모점수 x 2 + 추가점수', verbose_name='3인 추가점수'),
        ),
        migrations.AddField(
            model_name='operationscheme',
            name='extra_4_point',
            field=models.FloatField(default=1.0, help_text='윗짝지 1명, 아래짝지 3명인 모임에서, 4명이 모두 모였을 때 추가로 부여하는 점수입니다.\n아래짝지 1명 모이면 커모점수. 2명 모이면 커모점수 x 2. 3명 모이면 커모점수 x 3 + 추가점수', verbose_name='4인 추가점수'),
        ),
    ]
