# Generated by Django 2.0.6 on 2018-08-24 07:37

from django.db import migrations, models
import django.db.models.deletion
import photo_album.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='One Line Description')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='설명')),
                ('image', models.ImageField(upload_to=photo_album.models.get_album_photo_path, verbose_name='이미지')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_album.Album')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['-created'],
            },
        ),
    ]
