# Generated by Django 2.0.6 on 2018-08-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_album', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
