# Generated by Django 2.0.6 on 2018-08-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='file',
        ),
    ]
