# Generated by Django 2.0.6 on 2018-08-26 13:32

from django.db import migrations
import photo_album.fields
import photo_album.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_album', '0003_auto_20180826_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=photo_album.fields.ThumbnailImageField(upload_to=photo_album.models.get_album_photo_path),
        ),
    ]
