# Generated by Django 2.0.6 on 2018-09-24 16:35

import cafes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafephoto',
            name='image',
            field=models.ImageField(upload_to=cafes.models.get_cafe_photo_path, verbose_name='카페 사진'),
        ),
    ]
