# Generated by Django 2.0.6 on 2018-06-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnermeeting',
            options={'verbose_name': '짝지 모임', 'verbose_name_plural': '짝지 모임'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': '짝지', 'verbose_name_plural': '짝지'},
        ),
    ]
