# Generated by Django 2.0.6 on 2018-10-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermeeting',
            name='num_down_partner',
            field=models.SmallIntegerField(default=0, help_text='아래짝지의 수만 입력해주세요.', verbose_name='참여한 아래짝지 수'),
        ),
    ]
