# Generated by Django 2.0.6 on 2018-10-07 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        ('core', '0002_auto_20181007_1027'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMeetingFeed',
            fields=[
                ('instagram_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Instagram')),
                ('coffee_meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.CoffeeMeeting')),
            ],
            options={
                'verbose_name': '커모 사진',
                'verbose_name_plural': '커모 사진',
            },
            bases=('core.instagram',),
        ),
    ]
