# Generated by Django 2.0.6 on 2018-07-09 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'get_latest_by': ['-partner_year', '-partner_semester'], 'verbose_name': '짝지',
                     'verbose_name_plural': '짝지'},
        ),
    ]
