# Generated by Django 2.0.6 on 2018-07-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20180630_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='짝지 점수'),
        ),
    ]
