# Generated by Django 2.0.6 on 2018-07-09 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20180709_1154'),
        ('partners', '0003_auto_20180709_1119'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partners',
            unique_together={('partner_year', 'partner_semester', 'up_partner')},
        ),
    ]
