# Generated by Django 2.0.6 on 2018-10-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20181008_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermeeting',
            name='num_down_partner',
            field=models.SmallIntegerField(default=0, verbose_name='참여한 아래짝지 수'),
        ),
    ]
