# Generated by Django 2.0.6 on 2018-07-08 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20180708_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='up_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ActiveUser'),
        ),
    ]
