# Generated by Django 2.0.6 on 2018-10-09 19:36

from django.db import migrations, models
import partners.validators


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partnermeeting_num_down_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermeeting',
            name='num_coffee',
            field=models.SmallIntegerField(default=0, validators=[partners.validators.meeting_coffee_validator], verbose_name='마신 커피 수'),
        ),
        migrations.AlterField(
            model_name='partnermeeting',
            name='num_eat',
            field=models.SmallIntegerField(default=0, validators=[partners.validators.meeting_eat_validator], verbose_name='먹은 식사 수'),
        ),
    ]
