# Generated by Django 2.0.6 on 2018-10-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20181009_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermeeting',
            name='point',
            field=models.SmallIntegerField(default=0),
        ),
    ]
