# Generated by Django 2.0.6 on 2018-06-30 06:37

import accounts.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1학기'), (2, '2학기')], default=1, verbose_name='가입 학기'),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_year',
            field=models.PositiveSmallIntegerField(default=2018, validators=[accounts.validator.year_validator], verbose_name='가입 년도'),
        ),
    ]
