# Generated by Django 2.0.6 on 2018-08-01 07:43

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=accounts.models.get_profile_path, verbose_name='프로필 사진'),
        ),
    ]
