# Generated by Django 2.0.6 on 2018-06-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180630_0637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeuser',
            options={'verbose_name': '활동 회원', 'verbose_name_plural': '활동 회원'},
        ),
    ]
