# Generated by Django 2.0.6 on 2018-07-02 07:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180630_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1학기'), (2, '2학기')], default=accounts.models.get_default_semester, verbose_name='가입 학기'),
        ),
    ]
