# Generated by Django 2.0.6 on 2018-07-03 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180702_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeuser',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='입금 확인'),
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(choices=[('hum', '인문대학'), ('soc', '사회과학대학'), ('nat', '자연과학대학'), ('nur', '간호대학'), ('bus', '경영대학'), ('eng', '공과대학'), ('agr', '농업생명과학대학'), ('art', '미술대학'), ('law', '법과대학'), ('edu', '사범대학'), ('cbe', '생활과학대학'), ('vet', '수의과대학'), ('pha', '약학대학'), ('mus', '음악대학'), ('med', '의과대학'), ('cls', '자유전공학부'), ('uni', '연합전공'), ('cor', '연계전공')], max_length=3, verbose_name='단과대'),
        ),
    ]
