# Generated by Django 2.0.6 on 2018-07-03 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180703_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active', to=settings.AUTH_USER_MODEL),
        ),
    ]
