# Generated by Django 2.0.6 on 2018-07-04 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180703_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeuser',
            options={'get_latest_by': ['active_year', '-active_semester'], 'verbose_name': '활동 회원', 'verbose_name_plural': '활동 회원'},
        ),
    ]
