# Generated by Django 2.0.6 on 2018-06-28 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20180628_0529'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=1000, verbose_name='내용')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='제목')),
                ('meeting_date', models.DateTimeField(verbose_name='날짜 및 시간')),
                ('max_participants', models.PositiveIntegerField(blank=True, verbose_name='참석 인원')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('participants', models.ManyToManyField(to='accounts.ActiveUser', verbose_name='참석자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
