# Generated by Django 2.0.6 on 2018-06-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeeeducation',
            options={'verbose_name': '커피 교육', 'verbose_name_plural': '커피 교육'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': '모임', 'verbose_name_plural': '모임'},
        ),
        migrations.AlterModelOptions(
            name='officialmeeting',
            options={'verbose_name': '공식 모임', 'verbose_name_plural': '공식 모임'},
        ),
    ]
