# Generated by Django 2.0.6 on 2018-07-13 05:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='max_participants',
            field=models.PositiveSmallIntegerField(default=0, help_text='인원제한을 없애려면 0으로 설정하세요.', verbose_name='참석 인원'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 5, 36, 26, 404698, tzinfo=utc), verbose_name='날짜 및 시간'),
        ),
    ]
