# Generated by Django 2.0.6 on 2018-07-20 03:37

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('meetings', '0002_auto_20180719_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 3, 37, 59, 395889, tzinfo=utc),
                                       verbose_name='날짜 및 시간'),
        ),
    ]
