# Generated by Django 2.0.6 on 2018-07-15 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20180713_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 6, 48, 13, 19295, tzinfo=utc), verbose_name='날짜 및 시간'),
        ),
    ]
