# Generated by Django 2.0.6 on 2018-07-31 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20180722_1656'),
        ('meetings', '0002_auto_20180722_1635'),
    ]

    operations = [
    ]
