# Generated by Django 2.0.6 on 2018-08-01 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_merge_20180731_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 7, 43, 3, 639346, tzinfo=utc), verbose_name='날짜 및 시간'),
        ),
    ]
