# Generated by Django 2.0.6 on 2018-08-08 01:18

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_auto_20180807_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 1, 18, 9, 602984, tzinfo=utc), verbose_name='날짜 및 시간'),
        ),
    ]
