# Generated by Django 2.0.6 on 2018-12-02 23:26

from django.db import migrations, models
import photo_albums.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=photo_albums.models.get_album_photo_path, verbose_name='사진'),
        ),
    ]
