# Generated by Django 2.0.6 on 2018-08-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='for_new',
        ),
        migrations.AddField(
            model_name='form',
            name='purpose',
            field=models.CharField(default='survey', max_length=10),
        ),
    ]
