# Generated by Django 2.0.6 on 2018-07-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='for_new',
            field=models.BooleanField(default=False),
        ),
    ]
