# Generated by Django 2.0.6 on 2018-08-07 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_form_for_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='McqManyAnswer',
            new_name='ChoiceManyAnswer',
        ),
        migrations.RenameModel(
            old_name='McqOneAnswer',
            new_name='ChoiceOneAnswer',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', '텍스트 응답'), ('choice_one', '1개 선택 응답'), ('choice_many', '다수 선택 응답'), ('binary', '예 / 아니오 응답')], default='text', max_length=10),
        ),
    ]
