# Generated by Django 2.0.6 on 2018-07-12 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0003_auto_20180712_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='user',
        ),
        migrations.AddField(
            model_name='form',
            name='user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
