# Generated by Django 2.0.6 on 2018-08-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20180807_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', '텍스트 응답'), ('choice_one', '1개 선택 응답'), ('choice_many', '다수 선택 응답'), ('binary', '예 / 아니오 응답')], default='text', max_length=15),
        ),
    ]
