# Generated by Django 2.0.6 on 2018-08-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20180807_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-created']},
        ),
    ]
