# Generated by Django 2.0.6 on 2018-07-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20180712_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='opened',
            field=models.BooleanField(default=True),
        ),
    ]
