# Generated by Django 2.0.6 on 2018-07-22 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카페이름')),
                ('address', models.CharField(max_length=100, verbose_name='주소')),
                ('phone', models.CharField(help_text='0x-xxxx-xxxx 형식으로 입력해주세요', max_length=14, null=True, verbose_name='전화번호')),
                ('machine', models.CharField(max_length=100, null=True, verbose_name='에스프레소 머신')),
                ('grinder', models.CharField(max_length=100, null=True, verbose_name='그라인더')),
                ('price', models.CharField(choices=[('CHEAPEST', '~ 2천원'), ('CHEAP', '2천원 ~ 4천원'), ('MIDDLE', '4천원 ~ 6천원'), ('EXPENSIVE', '6천원 ~ 8천원'), ('MOST EXPENSIVE', '8천원 ~ ')], max_length=15, verbose_name='가격대')),
                ('from_time', models.TimeField(null=True, verbose_name='개점시간')),
                ('to_time', models.TimeField(null=True, verbose_name='폐점시간')),
                ('closed_day', models.CharField(choices=[('SUN', '일요일'), ('MON', '월요일'), ('TUE', '화요일'), ('WED', '수요일'), ('THU', '목요일'), ('FRI', '금요일'), ('SAT', '토요일')], max_length=3, null=True, verbose_name='휴무일')),
                ('closed_frq', models.CharField(choices=[('EVERY', '매주'), ('FIRST', '첫번째'), ('SECOND', '두번째'), ('THIRD', '세번째'), ('FOURTH', '네번째'), ('LAST', '마지막')], max_length=6, null=True, verbose_name='휴무 빈도')),
                ('closed_holiday', models.BooleanField(default=False, verbose_name='공휴일 휴무 여부')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
