# Generated by Django 2.0.6 on 2018-07-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe',
            options={'ordering': ['-created']},
        ),
    ]
