# Generated by Django 2.0.6 on 2018-07-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20180731_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='closed_day',
            field=models.CharField(blank=True, choices=[('SUN', '일요일'), ('MON', '월요일'), ('TUE', '화요일'), ('WED', '수요일'), ('THU', '목요일'), ('FRI', '금요일'), ('SAT', '토요일')], max_length=3, null=True, verbose_name='휴무일'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='closed_frq',
            field=models.CharField(blank=True, choices=[('EVERY', '매주'), ('FIRST', '첫번째'), ('SECOND', '두번째'), ('THIRD', '세번째'), ('FOURTH', '네번째'), ('LAST', '마지막')], max_length=6, null=True, verbose_name='휴무 빈도'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='from_time',
            field=models.TimeField(blank=True, null=True, verbose_name='개점시간'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='grinder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='그라인더'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='machine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='에스프레소 머신'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='phone',
            field=models.CharField(blank=True, help_text='0x-xxxx-xxxx 형식으로 입력해주세요', max_length=14, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='to_time',
            field=models.TimeField(blank=True, null=True, verbose_name='폐점시간'),
        ),
    ]
