# Generated by Django 2.0.6 on 2018-08-01 07:43

from django.db import migrations, models

import cafe.models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20180731_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='image',
            field=models.ImageField(blank=True, upload_to=cafe.models.get_cafe_photo_path, verbose_name='이미지'),
        ),
    ]
