# Generated by Django 2.0.6 on 2018-08-07 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_auto_20180801_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='link',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='링크'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='mapx',
            field=models.IntegerField(blank=True, null=True, verbose_name='x좌표'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='mapy',
            field=models.IntegerField(blank=True, null=True, verbose_name='y좌표'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='road_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='도로명주소'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='전화번호'),
        ),
    ]
